### ISSUE TITLE
Refreshing page results in a Server error?

### ISSUE THREAD

**Issue by Thundros** [nickyvanurk/3d-multiplayer-browser-shooter#1]
Hi @nickyvanurk! First off, I'd just like to say : EXCELLENT job on this! I have been waiting for something like this to come out on Three.js for a very, VERY long time now! :)

Secondly, I'd like to let you know & can confirm without a shadow of a doubt that the Server has an error when you refresh the client page with the server running.

I get the following error in the Server : 

`listening on 8080
events.js:174
      throw er; // Unhandled 'error' event`

Also, can you please add a 30 second live-checker on the client page & if the Server can't be connected to within 30 seconds, switch the 'Connecting....' status to : 'Server is :: { Offline... }' ?

Thank you!

**Comment by nickyvanurk** [comment]
Hi @Thundros, thanks for the kind words. The problem should be fixed now. I only had the problem when testing it in chrome, which is weird because I developed it using chrome 2 years ago. If you want you could implement that functionality for yourself, just make a pull request and I'll add it to the project if it's functional. I am planning to continue working on this project very soon though, much to improve. This project was created in two weeks so code standard wasn't at the top of my list ;) I focused mainly on improving the network protocol, making it buttery smooth.

**Comment by Thundros** [comment]
Hi, @nickyvanurk! You are most welcome! :) However, I am still getting : 

`listening on 8080
events.js:174
      throw er; // Unhandled 'error' event`

**Comment by nickyvanurk** [comment]
What browser are you using?
